name: "Setup CentOS7"
description: "Setup the CentOS7 container from manylinux"
inputs:
  openssl:
    description: 'OpenSSL'
    default: 0
runs:
  using: "composite"
  steps:
    - name: find openssl
      shell: sh
      run: |
        yum install -y epel-release yum-utils rpm-build
        yumdownloader --source openssl11
        rpm -ivh ./openssl11-1.1.1k-5.el7.src.rpm
        rpm --showrc | grep topdir
        yum-builddep -y openssl11
        # disable tests
        patch ~/rpmbuild/SPECS/openssl11.spec .github/actions/centos_7_setup/openssl.patch
        cd ~/rpmbuild/SPECS
        rpmbuild -bp openssl11.spec
        rpmbuild -ba openssl11.spec
        ls ~/rpmbuild/RPMS

    - name: install openssl
      shell: sh
      run: |
        yum install -y https://duckdb-rpms.s3.us-west-2.amazonaws.com/openssl11-devel-1.1.1k-5.el7.aarch64.rpm \
                       https://duckdb-rpms.s3.us-west-2.amazonaws.com/openssl11-libs-1.1.1k-5.el7.aarch64.rpm \
                       https://duckdb-rpms.s3.us-west-2.amazonaws.com/openssl11-static-1.1.1k-5.el7.aarch64.rpm \
                       https://duckdb-rpms.s3.us-west-2.amazonaws.com/openssl11-1.1.1k-5.el7.aarch64.rpm

    - uses: actions/upload-artifact@v3
      with:
        name: openssl-rpm
        path: ~/rpmbuild/RPMS

    - name: git version
      shell: sh
      run: git --version

    - name: Install dependencies
      shell: bash
      run: |
        yum install -y gcc gcc-c++ cmake make
        yum install -y epel-release
        yum install -y make gcc perl-core pcre-devel wget zlib-devel python3
        yum install -y git
        yum install -y curl-devel expat-devel gettext-devel zlib-devel perl-ExtUtils-MakeMaker ninja-build
        yum install -y java-11-openjdk-devel maven

    - name: Install AWS CLI
      shell: bash
      run: |
        python3 -m pip install awscli
        aws --version

      # the weird openssl findreplace fix with version numbers is from: https://github.com/h2o/h2o/issues/213
    - name: Download OpenSSL 1.1.1s
      shell: bash
      if: ${{ inputs.openssl == 1 }}
      run: |
        wget https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1s.tar.gz
        tar -xzvf OpenSSL_1_1_1s.tar.gz
        mv openssl-OpenSSL_1_1_1s openssl-1.1.1s
        cd openssl-1.1.1s
        find ./ -type f -exec sed -i -e 's/\#\ define\ OPENSSL\_VERSION\_NUMBER/\#define\ OPENSSL\_VERSION\_NUMBER/g' {} \;

    - name: Configure OpenSSL
      if: ${{ inputs.openssl == 1 }}
      shell: bash
      run: |
        cd openssl-1.1.1s
        ./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic

    - name: Build OpenSSL
      if: ${{ inputs.openssl == 1 }}
      shell: bash
      run: |
        cd openssl-1.1.1s
        make
        make install
