name: "Setup CentOS7"
description: "Setup the CentOS7 container from manylinux"
inputs:
  openssl:
    description: 'OpenSSL'
    default: '0'
  jdk:
    description: 'Whether to install OpenJDK and Maven'
    default: 'false'
runs:
  using: "composite"
  steps:
    #    - name: find openssl
    #      shell: sh
    #      run: |
    #        yum install -y epel-release yum-utils rpm-build
    #        yumdownloader --source openssl11
    #        rpm -ivh ./openssl11-1.1.1k-5.el7.src.rpm
    #        rpm --showrc | grep topdir
    #        yum-builddep -y openssl11
    #        # disable tests
    #        patch ~/rpmbuild/SPECS/openssl11.spec .github/actions/centos_7_setup/openssl.patch
    #        cd ~/rpmbuild/SPECS
    #        rpmbuild -bp openssl11.spec
    #        rpmbuild -ba openssl11.spec
    #        ls ~/rpmbuild/RPMS

    - name: git version
      shell: sh
      run: git --version

    - name: Install dependencies
      shell: bash
      run: |
        yum install -y gcc gcc-c++ cmake make
        yum install -y epel-release
        yum install -y make gcc perl-core pcre-devel wget zlib-devel python3
        yum install -y git
        yum install -y curl-devel expat-devel gettext-devel zlib-devel perl-ExtUtils-MakeMaker ninja-build

    - name: Install JDK
      if: inputs.jdk == 'true'
      shell: sh
      run: |
        yum install -y java-11-openjdk-devel maven

    - name: Install AWS CLI
      shell: bash
      run: |
        python3 -m pip install awscli
        aws --version

    - name: Install OpenSSL 1.1.1k
      shell: sh
      if: ${{ inputs.openssl == 1 }}
      run: |
        yum-config-manager --add-repo https://duckdb-rpms.s3.us-west-2.amazonaws.com/duckdb-rpms.repo
        yum install -y openssl11-devel openssl11-libs openssl11-static openssl11
