name: "Setup CentOS7"
description: "Setup the CentOS7 container from manylinux"
inputs:
  openssl:
    description: 'OpenSSL'
    default: '0'
  jdk:
    description: 'Whether to install OpenJDK and Maven'
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        yum install -y gcc gcc-c++ cmake make
        yum install -y epel-release
        yum install -y make gcc wget ninja-build

    - run: |
        yum install -y nodejs  # required for artifact upload, not included in manylinux images
        node --version
      shell: sh

    - name: Install JDK
      if: inputs.jdk == 'true'
      shell: sh
      run: |
        yum install -y java-11-openjdk-devel maven

    - run: echo "/opt/_internal/cpython-3.10.12/bin" >> $GITHUB_PATH

    - name: Install AWS CLI
      shell: bash
      run: |
        python3.10 -m pip install awscli
        aws --version

    - name: Install OpenSSL 1.1.1k
      shell: sh
      if: inputs.openssl == 1
      run: |
        yum-config-manager --add-repo https://duckdb-rpms.s3.us-west-2.amazonaws.com/duckdb-rpms.repo
        yum install -y openssl11-devel openssl11-libs openssl11-static openssl11
