[project]
name = "duckdb"
dynamic = ["version"]
description = 'DuckDB embedded database'
readme = {text = "See here for an introduction: https://duckdb.org/docs/api/python/overview", content-type = "markdown"}
keywords = ['DuckDB', 'Database', 'SQL', 'OLAP']
classifiers = [
    'Topic :: Database :: Database Engines/Servers',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
]
license = {text = "MIT"}
maintainers = [
    { name = "Hannes Muehleisen", email = "hannes@duckdblabs.com" }
]
dependencies = ['numpy']

[project.urls]
Documentation = "https://duckdb.org/docs/api/python/overview"
Source = "https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg"
Issues = "https://github.com/duckdb/duckdb/issues"
Changelog = "https://github.com/duckdb/duckdb/releases"

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]<7.0.0", "oldest-supported-numpy", 'pybind11>=2.6.0']
build-backend = "setuptools.build_meta"

# pyproject.toml
[tool.setuptools_scm]
root = "../.."

# Config for cibuildwheel, some values are overridden by env variables of specific jobs

# Default config runs all tests and requires at least one extension to be tested against
[tool.cibuildwheel]
before-build = 'pip install --prefer-binary "pandas>=0.24" "pytest>=4.3"'
before-test = 'pip install --prefer-binary "pandas>=0.24" pytest-timeout mypy "psutil>=5.9.0" && pip install --prefer-binary "requests>=2.26" && (pip install --prefer-binary "pyarrow>=8.0" || true)'
test-requires = 'pytest'
test-command = 'DUCKDB_PYTHON_TEST_EXTENSION_PATH={project} DUCKDB_PYTHON_TEST_EXTENSION_REQUIRED=1 python -m pytest {project}/tests'

# For musllinux we currently don't build extensions yet
[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
test-command = "python -m pytest {project}/tests/fast"

# For 32 bit we don't build extensions
[[tool.cibuildwheel.overrides]]
select = "*i686*"
test-command = "python -m pytest {project}/tests/fast"

[tool.cibuildwheel.windows]
test-command = "python -m pytest {project}/tests/fast"
