#pragma once

#include "duckdb/function/function_list.hpp"
#include "duckdb/core_functions/function_list.hpp"
#include "duckdb/core_functions/function_helpers.hpp"
#include "duckdb/function/scalar/operators_functions.hpp"

namespace duckdb {

// this list is generated by scripts/generate_functions.py
static StaticFunctionDefinition internal_functions[] = {
	DUCKDB_SCALAR_FUNCTION_SET_ALIAS(ModFunAlias),
	DUCKDB_SCALAR_FUNCTION_SET_ALIAS(MultiplyFunAlias),
	DUCKDB_SCALAR_FUNCTION_SET_ALIAS(AddFunAlias),
	DUCKDB_SCALAR_FUNCTION_SET_ALIAS(SubtractFunAlias),
	DUCKDB_SCALAR_FUNCTION_SET_ALIAS(DivideFunAlias),
	DUCKDB_SCALAR_FUNCTION_SET_ALIAS(DivideFunAlias2),
	DUCKDB_SCALAR_FUNCTION_SET(AddFun),
	DUCKDB_SCALAR_FUNCTION_SET(DivideFun),
	DUCKDB_SCALAR_FUNCTION_SET(ModFun),
	DUCKDB_SCALAR_FUNCTION_SET(MultiplyFun),
	DUCKDB_SCALAR_FUNCTION_SET(SubtractFun),
	FINAL_FUNCTION
};

StaticFunctionDefinition* OperatorFunctions::GetFunctions() {
	return internal_functions;
}
}