//===----------------------------------------------------------------------===//
//                         DuckDB
//
// duckdb/function/scalar/operators_functions.hpp
//
//
//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_functions.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#pragma once

#include "duckdb/function/function_set.hpp"

namespace duckdb {

struct AddFun {
	static constexpr const char *Name = "add";
	static constexpr const char *Parameters = "";
	static constexpr const char *Description = "";
	static constexpr const char *Example = "2 + 2";

	static ScalarFunctionSet GetFunctions();
	static ScalarFunction GetFunction(const LogicalType &left_type, const LogicalType &right_type);
	static ScalarFunction GetFunction(const LogicalType &type);
};

struct AddFunAlias {
	using ALIAS = AddFun;

	static constexpr const char *Name = "+";
};

struct SubtractFun {
	static constexpr const char *Name = "subtract";
	static constexpr const char *Parameters = "";
	static constexpr const char *Description = "";
	static constexpr const char *Example = "5 - 2";

	static ScalarFunctionSet GetFunctions();
	static ScalarFunction GetFunction(const LogicalType& left_type, const LogicalType& right_type);
	static ScalarFunction GetFunction(const LogicalType &type);
};

struct SubtractFunAlias {
	using ALIAS = SubtractFun;

	static constexpr const char *Name = "-";
};

struct MultiplyFun {
	static constexpr const char *Name = "multiply";
	static constexpr const char *Parameters = "";
	static constexpr const char *Description = "";
	static constexpr const char *Example = "2 * 2";

	static ScalarFunctionSet GetFunctions();
};

struct MultiplyFunAlias {
	using ALIAS = MultiplyFun;

	static constexpr const char *Name = "*";
};

struct DivideFun {
	static constexpr const char *Name = "divide";
	static constexpr const char *Parameters = "";
	static constexpr const char *Description = "";
	static constexpr const char *Example = "10 / 5";

	static ScalarFunctionSet GetFunctions();
};

struct DivideFunAlias {
	using ALIAS = DivideFun;

	static constexpr const char *Name = "/";
};

struct DivideFunAlias2 {
	using ALIAS = DivideFun;

	static constexpr const char *Name = "//";
};

struct ModFun {
	static constexpr const char *Name = "mod";
	static constexpr const char *Parameters = "";
	static constexpr const char *Description = "";
	static constexpr const char *Example = "11 % 2";

	static ScalarFunctionSet GetFunctions();
};

struct ModFunAlias {
	using ALIAS = ModFun;

	static constexpr const char *Name = "%";
};

} // namespace duckdb
