name: Build Python Extensions

jobs:
  build_python_extensions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: ./.github/actions/centos_7_setup
      with:
        openssl: 1

    - name: Version Check
      shell: bash
      run: |
        cmake --version
        ldd --version ldd
        ls -al
        pwd
        echo "$USER"

    - uses: ./.github/actions/build_extensions
      with:
        deploy_as: linux_arm64_gcc4
        s3_id: ${{ secrets.S3_ID }}
        s3_key: ${{ secrets.S3_KEY }}
        signing_pk: ${{ secrets.DUCKDB_EXTENSION_SIGNING_PK }}
        treat_warn_as_error: 0
        visualizer: 0
        icu: 0
        tpch: 0
        tpcds: 0
        httpfs: 0
        fts: 0
        json: 1
        excel: 0
        sqlsmith: 0
        inet: 0
        autocomplete: 0

    - uses: actions/upload-artifact@v3
      with:
        name: manylinux-extensions-aarch64
        path: |
          build/release/extension/*/*.duckdb_extension
