on: push

jobs:
  android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8.0.372+7
        distribution: temurin

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build SampleApplication
      run: |
        mkdir build/android
        cd build/android
        cmake -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ABI \
          -DANDROID_PLATFORM=android-$MINSDKVERSION \
          ..
        ninja
